//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbarAdreslemeLokasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class KutuAna
    {
        public int KutuID { get; set; }
        public string KutuNo { get; set; }
        public string Location { get; set; }
        public string Durum { get; set; }
        public Nullable<int> TerminalNo { get; set; }
        public string Aktarildi { get; set; }
    }
}
